name: Cloud Run Deployment Workflow

on:
  push:
    branches: [main]

env:
  PROJECT_ID: gabsdevops # TODO: update Google Cloud project id
  GAR_LOCATION: docker-registry # TODO: update Artifact Registry location
  SERVICE: dantas-stage # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region

jobs:
  deploy-backstage:
    permissions:
      contents: 'read'
      id-token: 'write'

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    
    name: Deploying Backstage
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        id: auth
        with:
          token_format: 'access_token'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: docker auth
        id: docker-auth
        uses: 'docker/login-action@v2'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

        # This example runs "docker login" directly to Artifact Registry.
      - name: docker login
        run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: yarn install
        uses: backstage/actions/yarn-install@v0.6.4
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}
  
      - name: yarn tsc
        run: | 
          yarn tsc

      - name: yarn lint
        run: | 
          yarn lint

      - name: yarn build
        run: | 
          yarn build:all
          ls
      
      - name: Build and Push Container
        run: |-
          docker build . -f packages/backend/Dockerfile -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest" 
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest"

      # - name: set up docker buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     file: ./packages/backend/Dockerfile
      #     push: true
      #     platforms: linux/amd64,linux/arm64
      #     tags: |
      #       "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest" 

      - name: 'deploy cloud-run'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          image: '"${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest"'
          service: '${{ env.PROJECT_ID }}'
